### PR TITLE
background is resonsive to changes

### PR DESCRIPTION
**Pull request by timeyyy**
Does this fix the issue for you?

### CODE REVIEW

**Comment by timeyyy** [comment]
issue #4 @ryanmorillo

**Comment by ryanmorillo** [comment]
Not pushed into pip yet?  I'll have to check tomorrow, but thanks.

**Comment by timeyyy** [comment]
pushed to pip

**Comment by ryanmorillo** [comment]
pytknvim_colors

**Comment by timeyyy** [comment]
@ryanmorillo could you tell me the colorscheme you are using

**Pull request merged**
